[package]
name = "godly-protocol"
version = "0.1.5"
edition = "2021"
license = "BUSL-1.1"

[dependencies]
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "snapshot_serialization"
harness = false
